import React from "react";

const Shop = () => {
  return (
    <div className="py-8 bg-white dark:bg-gray-900 dark:text-white duration-200 overflow-hidden">
      
      <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ad delectus dolorem commodi nobis non animi similique dolor, possimus sit minima incidunt tempore magnam pariatur quo qui suscipit autem molestias vitae nisi enim nesciunt quibusdam magni? Odio cumque, vitae dolorum, ipsum, accusamus cum dolore iure temporibus praesentium accusantium earum? Vel, earum laborum, quos aut officia, quia nulla consequatur harum adipisci saepe recusandae cupiditate eum minima ut? Aspernatur modi sapiente ab neque atque quod perspiciatis delectus esse dolor adipisci enim, excepturi nesciunt, blanditiis eos. A, voluptatem in praesentium possimus quis, dignissimos corrupti blanditiis at fugit atque enim nulla tempore quibusdam recusandae eligendi provident aut necessitatibus facere illo ipsum odio. Maiores exercitationem dolore quis ea, in officiis repudiandae vero dolorem. Soluta itaque dolorum assumenda sint laudantium voluptatem alias ipsum magni neque excepturi quidem perspiciatis molestiae delectus maiores quas, accusantium magnam accusamus dolores distinctio repellat eum deleniti consequuntur. Corporis maxime provident ipsum suscipit neque, magni a aliquam voluptatem non, eos, reiciendis ab natus. Illo voluptates veritatis sunt possimus esse, odit delectus eius aut provident praesentium adipisci ipsa consequatur iusto. At tempore architecto earum dolores? Eum repellat cupiditate temporibus saepe fugiat harum, minima autem reprehenderit veniam hic nesciunt laborum ad alias sapiente, accusamus maiores quae odit quam beatae laudantium, animi aliquam quibusdam commodi nulla. Fugit temporibus veritatis nam pariatur dolor similique saepe eveniet laboriosam, fuga dolorem, minima natus adipisci aperiam, officia quibusdam iure mollitia tempore? Vero nihil praesentium corporis sapiente, facilis a voluptatum amet iure eveniet ipsum at! Consequatur explicabo tempora laborum, corrupti tenetur accusamus itaque, voluptatum nihil incidunt asperiores ipsa quia veniam sapiente rerum mollitia inventore pariatur! Ut voluptate magni illo assumenda a rerum dolore omnis atque optio nostrum alias doloremque nobis ab est, fugit necessitatibus dignissimos odio laborum eveniet asperiores. Eum omnis assumenda deserunt, quaerat ullam autem porro officia expedita labore! Laboriosam dolorem repellendus quibusdam porro sint obcaecati fugit nulla possimus animi. Nostrum accusantium repellat asperiores culpa, omnis, ullam obcaecati perferendis ducimus cupiditate vitae similique nulla expedita explicabo. Velit, adipisci aliquid consectetur, assumenda veritatis fugiat minus sed temporibus rerum fuga non quam porro.</div>
    </div>
  );
};

export default Shop;
